import { columnKriteria } from "@/app/dashboard/(dashboard-pages)/kriteria-benefit/data-column-kriteria";
import { DataTable } from "@/components/data-table";
import { getDataKriteria, KriteriaType } from "@/lib/data-fetch";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Kriteria Benefit",
  description: "Generated by create next app",
};
const DataKriteriaPage = async () => {
  const data = await getDataKriteria({ type: KriteriaType.BENEFIT });
  if (!data) {
    return <div className="w-full p-10 text-center text-2xl font-bold">Data not found</div>;
  }

  return (
    <section className="container mx-auto p-10">
      <h1 className="mb-5 text-3xl font-bold">Data Kriteria Benefit Page</h1>
      <DataTable data={data} columns={columnKriteria} title="kriteria" searchBy="nama_kriteria" />
    </section>
  );
};

export default DataKriteriaPage;
