import FormInputriteria from "@/components/pages/kriteria/form-input-kriteria";
import { getDataKriteriaById } from "@/lib/data-fetch";
import { ChevronLeft } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";

export const metadata: Metadata = {
  title: "SPK | Ubah Data Kriteria",
  description: "Generated by create next app",
};
const EditDataKriteriaPage = async ({ params }: { params: Promise<{ id: string }> }) => {
  const id = (await params).id;
  const data = await getDataKriteriaById(id);

  if (!data) return notFound();
  return (
    <section className="flex w-full justify-between p-10">
      <Link href="/dashboard/kriteria-benefit" className="mb-5 mt-5 flex h-10 w-10 items-center justify-center rounded-full bg-black dark:bg-white text-3xl font-bold">
        <ChevronLeft className="text-2xl text-white dark:text-black" />
      </Link>
      <FormInputriteria title="Ubah Data Kriteria Benefit" data={data} />
      <p className="hidden opacity-0 lg:block">menuss</p>
    </section>
  );
};

export default EditDataKriteriaPage;
