import FormInputKaryawan from "@/components/pages/karyawan/form-input-karyawan";
import { getDataKaryawanById } from "@/lib/data-fetch";
import { ChevronLeft } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Ubah Data Karyawan",
  description: "Generated by create next app",
};
const EditDataKaryawanPage = async ({ params }: { params: Promise<{ id: string }> }) => {
  const id = (await params).id;
  const data = await getDataKaryawanById(id);

  if (!data) return notFound();
  return (
    <section className="flex w-full justify-between p-10">
      <Link href="/dashboard/karyawan" className="mb-5 mt-5 flex h-10 w-10 items-center justify-center rounded-full bg-black dark:bg-white text-3xl font-bold">
        <ChevronLeft className="text-2xl text-white dark:text-black" />
      </Link>
      <FormInputKaryawan type="edit" title="Ubah Data Karyawan" data={data} />
      <p className="hidden opacity-0 lg:block">menuss</p>
    </section>
  );
};

export default EditDataKaryawanPage;
