import FormInputBobot from "@/components/pages/bobot/form-input-bobot";
import { getDataBobotById, getDataKriteria } from "@/lib/data-fetch";
import { ChevronLeft } from "lucide-react";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Ubah Data Bobot",
  description: "Generated by create next app",
};

const EditDataBobotPage = async ({ params }: { params: Promise<{ id: string }> }) => {
  const id = (await params).id;
  const data = await getDataBobotById(id);
  const dataKriteria = await getDataKriteria({});

  if (!data) return notFound();

  const formattedData = {
    id: data.id,
    id_kriteria: data.kriteria.id,
    nama_kriteria: data.kriteria.nama_kriteria,
    tipe_kriteria: data.kriteria.type,
    nilai_bobot: data.nilai_bobot,
  };

  return (
    <section className="flex w-full justify-between p-10">
      <Link href="/dashboard/bobot" className="mb-5 mt-5 flex h-10 w-10 items-center justify-center rounded-full bg-black dark:bg-white text-3xl font-bold">
        <ChevronLeft className="text-2xl text-white dark:text-black" />
      </Link>
      <FormInputBobot type="edit" title="Ubah Data Bobot" dataKriteria={dataKriteria!} data={formattedData} />
      <p className="hidden opacity-0 lg:block">menuss</p>
    </section>
  );
};

export default EditDataBobotPage;
