import { DataTable } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import { getDataPenilaianMatrix, getDetailPenilainMatrix } from "@/lib/data-fetch";
import Link from "next/link";
import { columnPenilaianSawBenefit } from "@/app/dashboard/(dashboard-pages)/penilaian-saw-benefit/data-column-penilaian-saw-benefit";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Penilaian SAW Benefit",
  description: "Generated by create next app",
};
export interface PenilaianSAWBenefitProps {
  id: string;
  id_penilaian_matrix: string;
  nama_karyawan?: string;
  komunikasi: number;
  etika: number;
  kinerja: number;
  kreativitas: number;
  kedisiplinan: number;
  nilai_akhir: number;
}

const PenilaianSAWPage = async () => {
  const dataPenilaianMatrix = await getDataPenilaianMatrix();
  const dataPenilaianDetailMatrix = await getDetailPenilainMatrix({});

  if (!dataPenilaianMatrix || !dataPenilaianDetailMatrix) return null;
  const formattedData = dataPenilaianDetailMatrix?.data_detail_penilaian.map((item) => {
    return {
      id: item.id,
      id_penilaian_matrix: item.id_penilaian_matrix,
      nama_karyawan: dataPenilaianMatrix?.find((matrix) => matrix.id === item.id_penilaian_matrix)?.karyawan?.nama_karyawan,
      komunikasi: item.komunikasi,
      etika: item.etika,
      kinerja: item.kinerja,
      kreativitas: item.kreativitas,
      kedisiplinan: item.kedisiplinan,
      nilai_akhir: item.nilai_akhir,
    };
  });

  const sortedData = formattedData?.sort((a, b) => b.nilai_akhir - a.nilai_akhir);

  const componentLink = () => {
    return (
      <Link href="/dashboard/penilaian-saw-benefit/add-new" className="flex items-center px-3">
        <Button variant="default" className="h-8">
          Add New
        </Button>
      </Link>
    );
  };
  return (
    <section className="container mx-auto p-10">
      <h1 className="mb-5 text-3xl font-bold">Data Penilaian SAW Benefit Page</h1>
      <DataTable data={sortedData} columns={columnPenilaianSawBenefit} elements={componentLink()} title="nama karyawan" searchBy="nama_karyawan" />
    </section>
  );
};

export default PenilaianSAWPage;
