import FormInputKaryawan from "@/components/pages/karyawan/form-input-karyawan";
import { ChevronLeft } from "lucide-react";
import Link from "next/link";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Tambah Data Karyawan",
  description: "Generated by create next app",
};
const AddDataKaryawanPage = () => {
  return (
    <section className="flex w-full justify-between p-10">
      <Link href="/dashboard/karyawan" className="mb-5 mt-5 flex h-10 w-10 items-center justify-center rounded-full bg-black dark:bg-white text-3xl font-bold">
        <ChevronLeft className="text-2xl text-white dark:text-black" />
      </Link>
      <FormInputKaryawan type="add" title="Tambah Data Karyawan" />
      <p className="hidden opacity-0 lg:block">menuss</p>
    </section>
  );
};

export default AddDataKaryawanPage;
