import { DataTable } from "@/components/data-table";
import { Button } from "@/components/ui/button";
import { getDataKaryawan } from "@/lib/data-fetch";
import Link from "next/link";
import { columnKaryawan } from "@/app/dashboard/(dashboard-pages)/karyawan/data-column-karyawan";
import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Karyawan",
  description: "Generated by create next app",
};

export interface DataKaryawanProps {
  id: string;
  user_id?: string;
  nama_atasan?: string;
  nama_karyawan: string;
  no_telp: string;
  alamat: string;
}

const DataKaryawanPage = async () => {
  const data = await getDataKaryawan({});
  if (!data) {
    return <div className="w-full p-10 text-center text-2xl font-bold">Data not found</div>;
  }
  const transformedData = data.map((item) => {
    return {
      id: item.id,
      user_id: item.user_id,
      nama_atasan: item.user.nama,
      nama_karyawan: item.nama_karyawan,
      no_telp: item.no_telp,
      alamat: item.alamat,
    };
  });
  const componentLink = () => {
    return (
      <Link href="/dashboard/karyawan/add-new" className="flex items-center px-3">
        <Button variant="default" className="h-8">
          Add New
        </Button>
      </Link>
    );
  };
  return (
    <section className="container mx-auto p-10">
      <h1 className="mb-5 text-3xl font-bold">Data Karyawan Page</h1>
      <DataTable data={transformedData} columns={columnKaryawan} elements={componentLink()} title="nama karyawan" />
    </section>
  );
};

export default DataKaryawanPage;
