import FormInputPenilaianSAW from "@/components/pages/penilaian-saw/form-input-penilaian-saw";
import { getDataBobot, getDataKaryawan, KriteriaType } from "@/lib/data-fetch";
import { ChevronLeft } from "lucide-react";
import { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "SPK | Tambah Data Penilaian SAW Benefit",
  description: "Generated by create next app",
};

const AddDataPenilaianPage = async () => {
  const dataBobot = await getDataBobot(KriteriaType.BENEFIT);
  const dataKaryawan = await getDataKaryawan({ isPenilaian: false });
  if (!dataBobot) return <div className="w-full p-10 text-center text-2xl font-bold">Data bobot not found</div>;
  if (!dataKaryawan) return <div className="w-full p-10 text-center text-2xl font-bold">Data karyawan not found</div>;

  const formattedDataBobot = dataBobot.map((item) => {
    return {
      id: item.id,
      id_kriteria: item.kriteria.id,
      nama_kriteria: item.kriteria.nama_kriteria,
      tipe_kriteria: item.kriteria.type,
      nilai_bobot: item.nilai_bobot,
    };
  });
  return (
    <section className="flex w-full justify-between p-10">
      <Link href="/dashboard/penilaian-saw-benefit" className="mb-5 mt-5 flex h-10 w-10 items-center justify-center rounded-full bg-black dark:bg-white text-3xl font-bold">
        <ChevronLeft className="text-2xl text-white dark:text-black" />
      </Link>
      <FormInputPenilaianSAW title="Tambah Data Penilaian SAW Benefit" dataKaryawan={dataKaryawan} dataBobot={formattedDataBobot} />
      <p className="hidden opacity-0 lg:block">menuss</p>
    </section>
  );
};

export default AddDataPenilaianPage;
