import { Metadata } from "next";

export const metadata: Metadata = {
  title: "SPK | Dashboard",
  description: "Generated by create next app",
};

const Dashboard = () => {
  return (
    <div>
      <h3>ini adalah Dashboard</h3>
    </div>
  );
};

export default Dashboard;
